### ISSUE TITLE
Feature request: Internal shell (make hollow)

### ISSUE THREAD

**Issue by rozza-m** [JeremSparte/BHToolset#1]
Loving this set so far, though I've never used Houdini before!

Would it be possible / useful to add the ability to make a hollow shell? An example use might be to print a hollow form that can then be directly filled with resin or concrete for strength.

Thanks for your work!

**Comment by JeremSparte** [comment]
Hello, glad you like it !

You have the tool called [BH Mold](https://github.com/JeremSparte/BHToolset?tab=readme-ov-file#bh-mold) that does exactly what you are looking for if I understood correctly.
In the free library on [Thingiverse](https://www.thingiverse.com/sardou3d/designs) or [Cults 3D](https://cults3d.com/en/users/SarDou3D), for every hold file you have another one called *_Mold.stl, this one is the shell.

I hope it suits you, if this is not the case, do not hesitate to write me again, thank you for the feedback !

**Comment by rozza-m** [comment]
Hi, thanks for your quick reply. I did find that but it's not quite what I'm after. Sorry for not being clear.

BH Mould makes a negative that resin can be poured into, and then you're left with a hold made out of resin with the colour of the resin.

I'm suggesting to make a positive, but just a hollow one. So imagine that the front surface of the hold is 3d printed in whatever wonderful colours and fuzzy-skin texture I want - but for rigidity the inside is filled with resin or concrete that I've been able to achieve because the back side is a big hole that I can pour it into.

**Comment by rozza-m** [comment]
So the 3d model youd end up with would have the outer dimensions of the "naked" hold, then a configurable thickness, and then hollow in the middle. 

Probably achieved by just offsetting the surface of the object *inwards* and then subtracting from the original- but I have zero skills in Houdini!

**Comment by JeremSparte** [comment]
I added this feature [(see here)](https://github.com/JeremSparte/BHToolset?tab=readme-ov-file#bh-hollow).
It can be painful to print, do not hesitate to give feedback !

**Comment by rozza-m** [comment]
😍😍Amazing! Thank you!
